// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI-powered mission suggestion flow for personalized user guidance.
 *
 * - suggestMissions - A function that suggests personalized missions based on user class and progress.
 * - SuggestMissionsInput - The input type for the suggestMissions function, including user class, stats, and preferences.
 * - SuggestMissionsOutput - The return type for the suggestMissions function, listing suggested missions with descriptions.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const SuggestMissionsInputSchema = z.object({
  userClass: z
    .enum(['Warrior', 'Scholar', 'Tycoon'])
    .describe('The user selected class.'),
  strength: z.number().describe('The user strength stat.'),
  intelligence: z.number().describe('The user intelligence stat.'),
  wealth: z.number().describe('The user wealth stat.'),
  preferredMissionTypes: z
    .array(z.string())
    .describe('The user preferred mission types.'),
});
export type SuggestMissionsInput = z.infer<typeof SuggestMissionsInputSchema>;

const SuggestMissionsOutputSchema = z.object({
  suggestedMissions: z
    .array(
      z.object({
        title: z.string().describe('The title of the suggested mission.'),
        description: z.string().describe('A brief description of the mission.'),
        type: z.string().describe('The type of mission (e.g., Fitness, Knowledge, Wealth).'),
        rewardXp: z.number().describe('The XP reward for completing the mission.'),
      })
    )
    .describe('A list of suggested missions tailored to the user.'),
});
export type SuggestMissionsOutput = z.infer<typeof SuggestMissionsOutputSchema>;

export async function suggestMissions(input: SuggestMissionsInput): Promise<SuggestMissionsOutput> {
  return suggestMissionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestMissionsPrompt',
  input: {
    schema: z.object({
      userClass: z
        .enum(['Warrior', 'Scholar', 'Tycoon'])
        .describe('The user selected class.'),
      strength: z.number().describe('The user strength stat.'),
      intelligence: z.number().describe('The user intelligence stat.'),
      wealth: z.number().describe('The user wealth stat.'),
      preferredMissionTypes: z
        .array(z.string())
        .describe('The user preferred mission types.'),
    }),
  },
  output: {
    schema: z.object({
      suggestedMissions: z
        .array(
          z.object({
            title: z.string().describe('The title of the suggested mission.'),
            description: z.string().describe('A brief description of the mission.'),
            type: z.string().describe('The type of mission (e.g., Fitness, Knowledge, Wealth).'),
            rewardXp: z.number().describe('The XP reward for completing the mission.'),
          })
        )
        .describe('A list of suggested missions tailored to the user.'),
    }),
  },
  prompt: `You are an AI mentor in LevelUp Earth, a game that helps users improve their real-life skills.
Based on the user's class, stats, and preferred mission types, suggest 3 personalized missions.

User Class: {{{userClass}}}
Strength: {{{strength}}}
Intelligence: {{{intelligence}}}
Wealth: {{{wealth}}}
Preferred Mission Types: {{#each preferredMissionTypes}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}

Format the suggested missions as a JSON array of objects, each with a title, description, type (Fitness, Knowledge, or Wealth), and rewardXp. Give rewardXp values appropriate for the mission difficulty, with harder missions giving higher rewardXp values.
`,
});

const suggestMissionsFlow = ai.defineFlow<
  typeof SuggestMissionsInputSchema,
  typeof SuggestMissionsOutputSchema
>(
  {
    name: 'suggestMissionsFlow',
    inputSchema: SuggestMissionsInputSchema,
    outputSchema: SuggestMissionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
